apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: openshift-gitops
spec:
  project: 622162-project  # Ensure it matches the ArgoCD project name
  source:
    repoURL: "https://github.com/Pathivada-Varshini/argocd-lab.git"
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: 622162-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
