apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: 622162-project
  namespace: openshift-gitops
spec:
  description: "Project for ArgoCD deployment"
  sourceRepos:
    - "https://github.com/Pathivada-Varshini/argocd-lab.git"
  destinations:
    - namespace: 622162-project
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
